/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_example_ffmpeg_FFmpegCmd */

#ifndef _Included_com_example_example_ffmpeg_FFmpegCmd
#define _Included_com_example_example_ffmpeg_FFmpegCmd
#ifdef __cplusplus
#endif
/*
 * Class:     com_example_example_ffmpeg_FFmpegCmd
 * Method:    exec
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_example_ffmpeg_FFmpegCmd_exec
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
#endif
#endif
