/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_example_ffmpeg_FfmpegManager */

#ifndef _Included_com_example_example_ffmpeg_FfmpegManager
#define _Included_com_example_example_ffmpeg_FfmpegManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_example_ffmpeg_FfmpegManager
 * Method:    ffmpegRun
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_example_ffmpeg_FfmpegManager_ffmpegRun
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
